ResRev/urls.py
from django.urls import path, include
from . import views
from django.views.generic import TemplateView


app_name='ResRev'

urlpatterns = [
    path('', TemplateView.as_view(template_name="FrontPage.html"), name='frontPage'),
    path('register/',TemplateView.as_view(template_name="register.html"), name='register'),
	path('registering/', views.registering ,name='registering'),
	path('login/', views.login, name='login'),
	path('logout/', views.logout, name='logout'),
	path('new_rest/', TemplateView.as_view(template_name="new_rest.html"), name='new_rest'),
	path('add_rest/', views.add_rest ,name='add_rest'),
	path('home/', views.home, name='home'),
	path('restaurant/<int:rest_id>/add_review/', views.add_review, name='add_review'),
	path('restaurant/<int:rest_id>', views.restau , name='restau'),
]


        # <form action="{% url 'ResRev:signIn' %}" method="post">
        # {% csrf_token %}
		# <h2>Login</h1>
		# <div style="background-color:#e5e5e5;padding:15px;text-align:left;">
		# 	<input type="text" name="enter_name" placeholder="Enter your Name"><br><br>
		# 	<input type="text" name="enter_password" placeholder="Enter your Password"><br><br>
		# 	<input type="submit" value="OK">
		# </div>
        # </form>

webReview/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ResRev/', include('ResRev.urls')),
]

ResRev/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator



class Reviewer(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
    like = models.IntegerField(default=0)
    clas = models.TextField(default="Normal")
    description = models.TextField()
    contact = models.CharField(max_length=80)
    hours = models.IntegerField(default=0)

class Restaurant(models.Model):
    name = models.CharField(max_length=30)
    contact = models.CharField(max_length=80)
    description = models.TextField()
    category = models.TextField()
    rating = models.FloatField(default=0)
    g_rating = models.FloatField(default=0)
    # photo

class Review(models.Model):
    restau = models.ForeignKey(Restaurant,on_delete=models.CASCADE)
    reviewer = models.ForeignKey(Reviewer,on_delete=models.CASCADE)
    comment = models.TextField()
    rating = models.FloatField(validators=[MinValueValidator(1.0), MaxValueValidator(5.0)],)
    like = models.IntegerField(default=0)

ResRev/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .models import Reviewer, Restaurant, Review
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.urls import reverse

from django.http import HttpResponse, HttpResponseRedirect



def registering(request):
    if(request.POST['username']==""):
        return render(request, 'Register.html',{"err" : "Please Insert Username" },)
    elif(request.POST['password']!=request.POST['Cpassword']):
        return render(request, 'Register.html',{"err" : "Password is not correct" },)
    elif(request.POST['name']=="" or request.POST['contact']==""):
        return render(request, 'Register.html',{"err" : "Please Insert Name and Contact" },)
    else:
        user = User.objects.create_user(username=request.POST['username'], password=request.POST['password']
        ,first_name=request.POST['name'])
        Reviewer.objects.create(user=user,contact=request.POST['contact'])
        return render(request,'FrontPage.html',{'err':"Register Success!"})

def login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        auth_login(request, user)
        return redirect('/ResRev/home/')
    else:
        return render(request,'FrontPage.html',{'err': "Error, username or password is not correct"})

def logout(request):
    auth_logout(request)
    return render(request,'FrontPage.html',{'err': "Log Out Complete!"})


def add_rest(request):
    if(request.POST['name'] and request.POST['descrip'] and request.POST['contact'] and request.POST['cate']):
        Restaurant.objects.create(name=request.POST['name'],contact=request.POST['contact'],description=request.POST['descrip'],category=request.POST['cate'])
        return render(request, 'FrontPage.html',{'err': "Add Restaurant Success!"})
    else:
        return render(request,'new_rest.html',{'err': "Error, Please Fill all the Boxes below"})

def home(request):
    list_restau = Restaurant.objects.filter()
    return render(request,'home.html',{'list_restau':list_restau})

def restau(request,rest_id):
    rest_info = Restaurant.objects.get(id=rest_id)
    list_review = Review.objects.filter(restau=rest_id)
    return render(request,'restaurant_page.html',{'rest_info':rest_info,'list_review':list_review})

def add_review(request,rest_id):
    if(request.user.get_username() and request.POST['Rating']):
        rest = Restaurant.objects.get(id=rest_id)
        US = User.objects.get(username=request.user.get_username())
        Rv = Reviewer.objects.get(user=US)
        Review.objects.create(restau=rest,reviewer=Rv,comment=request.POST['comment'],rating=request.POST['Rating'])
        cal_rating = Review.objects.filter(restau=rest_id)
        rate = 0
        for i in range (Review.objects.filter(restau=rest_id,).count()) :
            rate = rate + cal_rating[i].rating
        rest.rating=rate/Review.objects.filter(restau=rest_id,).count()
        rest.save()
        return HttpResponseRedirect(reverse('ResRev:restau', args=(rest_id,)))
    else:
        return render(request,'restaurant_page.html',{'rest_info':rest_info,'list_review':list_review,'err':"Please Fill all the information"})

ResRev/templates/FrontPage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<style>
	body {margin:0;}

	font-family: Arial;
	}

	* {
	box-sizing: border-box;
	}

	fieldset {
  display: block;
  margin-left: 10px;
  margin-right: 2px;
  padding-top: 0.35em;
  padding-bottom: 0.625em;
  padding-left: 0.75em;
  padding-right: 0.75em;
  border: 2px groove (internal value);
  width:300px;
	font-size:18px;
	}

	.button {
	  background-color: #4CAF50; /* Green */
	  border: none;
	  color: white;
	  padding: 16px 32px;
	  text-align: center;
	  text-decoration: none;
	  display: inline-block;
	  font-size: 16px;
		margin-left: 10px;
	  margin-right: 2px;
	  -webkit-transition-duration: 0.4s; /* Safari */
	  transition-duration: 0.4s;
	  cursor: pointer;
	}
	.button1 {
	  background-color: white;
	  color: black;
	  border: 2px solid #000000;
		position: relative;
	}

	.button1:hover {
	  background-color: #000000;
	  color: white;
	}

	ul {
	  list-style-type: none;
	  margin: 0;
	  padding: 0;
	  overflow: hidden;
	  background-color: black	;
	  position: fixed;
	  top: 0;
	  width: 100%;
	}

	li {
	  float: left;
	}

	li a {
	  display: block;
	  color: white;
	  text-align: center;
	  padding: 14px 16px;
	  text-decoration: none;
	}

	.rightmenu {
	  background-color: green;
	}
	</style>
</head>
	<body>
	<ul>
	  <li><a>ResRev</a></li>
	</ul>
	{% if some_flag %}
    <div id="some_flag" title="Some Flag">
        <p>Register Finished!</p>
    </div>
	{% endif %}
		<br><br><h2>{{ err }}</h2>
		<form action="{% url 'ResRev:login' %}" method="post">
		{% csrf_token %}
		<br><br>
		<fieldset>
		 <legend><h2>Login</h2></legend>
			Username: <input type="text" name="username" placeholder="Username"><br><br>
			Password: <input type="password" name="password" placeholder="Password"><br><br>
			<input type="submit" value="Sign In">
		</fieldset>
	</form>

				<form action="{% url 'ResRev:register' %}" method="get">
				<br><input type="submit" class="button button1" value="Sign Up">
  			</form>

				<form action="{% url 'ResRev:new_rest' %}" method="get">
				<br><input type="submit" class="button button1" value="Add Restaurant">
  			</form>

				<form action="{% url 'ResRev:home' %}" method="get">
				<br><input type="submit" class="button button1" value="Guest">
  			</form>
	</body>
</html>

ResRev/templates/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<style>
	body {margin:0;}

	font-family: Arial;
	}

	* {
	box-sizing: border-box;
	}

	fieldset {
  display: block;
  margin-left: 10px;
  margin-right: 2px;
  padding-top: 0.35em;
  padding-bottom: 0.625em;
  padding-left: 0.75em;
  padding-right: 0.75em;
  border: 2px groove (internal value);
  width:300px;
	font-size:18px;
	}
	.left {
	  float:left;
	  width:50%;
	}
	.right {
	  float:left;
	  width:50%;
	}
	.button {
	  background-color: #4CAF50; /* Green */
	  border: none;
	  color: white;
	  padding: 16px 32px;
	  text-align: center;
	  text-decoration: none;
	  display: inline-block;
	  font-size: 16px;
		margin-left: 10px;
	  margin-right: 2px;
	  -webkit-transition-duration: 0.4s; /* Safari */
	  transition-duration: 0.4s;
	  cursor: pointer;
	}
	.button1 {
	  background-color: white;
	  color: black;
	  border: 2px solid #000000;
		position: relative;
	}

	.button1:hover {
	  background-color: #000000;
	  color: white;
	}
	.rightmenu {
	  background-color: green;
	}
	ul {
	  list-style-type: none;
	  margin: 0;
	  padding: 0;
	  overflow: hidden;
	  background-color: black	;
	  position: fixed;
	  top: 0;
	  width: 100%;
	}

	li {
	  float: left;
	}

	li a {
	  display: block;
	  color: white;
	  text-align: center;
	  padding: 14px 16px;
	  text-decoration: none;
	}

	.rightmenu {
	  background-color: green;
	}
	</style>
</head>
	<body>
	<ul>
	  <li><a>ResRev</a></li>
		{% if user.is_authenticated %}
			<li style="float:right"><a class="rightmenu" href="{% url 'ResRev:logout' %}">LogOut</a></li>
		{% else %}
		  <li style="float:right"><a class="rightmenu" href="{% url 'ResRev:frontPage' %}">LogIn</a></li>
		{% endif %}
	</ul>
	<div class="left">
		<tr>
			<form method="get">
			<h3>Restaurant Search<h3>
			<input type="text" name="search_res" placeholder="Enter your Name"><br><br>
			<input type="submit" class="button button1" value="search">
			</form>
		</tr>
	</div>
	<div class="right">
		<tr>
			<form action="{% url 'ResRev:new_rest' %}" method="get">
				<h3>Reviewer Search<h3>
				<input type="text" name="search_res" placeholder="Enter your Name"><br><br>
				<input type="submit" class="button button1" value="search">
			</form>
		</tr>
	</div>
	{% if some_flag %}
    <div id="some_flag" title="Some Flag">
        <p>Register Finished!</p>
    </div>
	{% endif %}

		<br><br><h2>{{ err }}</h2>
		<form action="{% url 'ResRev:login' %}" method="post">
		{% csrf_token %}
		<br><br>
		<fieldset>
		 <legend><h2>Restaurant List</h2></legend>
		 {% for name in list_restau %}
			 <a href="{% url 'ResRev:restau' name.id %}">{{ name.name }}</a><br>
		 {% endfor %}
		</fieldset>
	</form>

	</body>
</html>

ResRev/templates/new_rest.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<style>
	body {margin:0;}

	font-family: Arial;
	}

	* {
	box-sizing: border-box;
	}

	fieldset {
  display: block;
  margin-left: 10px;
  margin-right: 2px;
  padding-top: 0.35em;
  padding-bottom: 0.625em;
  padding-left: 0.75em;
  padding-right: 0.75em;
  border: 2px groove (internal value);
  width:300px;
	font-size:18px;
	}

	.button {
	  background-color: #4CAF50; /* Green */
	  border: none;
	  color: white;
	  padding: 16px 32px;
	  text-align: center;
	  text-decoration: none;
	  display: inline-block;
	  font-size: 16px;
		margin-left: 10px;
	  margin-right: 2px;
	  -webkit-transition-duration: 0.4s; /* Safari */
	  transition-duration: 0.4s;
	  cursor: pointer;
	}
	.button1 {
	  background-color: white;
	  color: black;
	  border: 2px solid #000000;
		position: relative;
	}

	.button1:hover {
	  background-color: #000000;
	  color: white;
	}

	ul {
	  list-style-type: none;
	  margin: 0;
	  padding: 0;
	  overflow: hidden;
	  background-color: black	;
	  position: fixed;
	  top: 0;
	  width: 100%;
	}

	li {
	  float: left;
	}

	li a {
	  display: block;
	  color: white;
	  text-align: center;
	  padding: 14px 16px;
	  text-decoration: none;
	}

	.rightmenu {
	  background-color: green;
	}
	</style>
</head>
	<body>


	<ul>
	  <li><a>ResRev</a></li>
		<li style="float:right"><a class="rightmenu" href="{% url 'ResRev:logout' %}">LogOut</a></li>
		{% if user.is_authenticated %}
			<li style="float:right"><a class="rightmenu" href="{% url 'ResRev:logout' %}">LogOut</a></li>
		{% else %}
			<li style="float:right"><a class="rightmenu" href="{% url 'ResRev:frontPage' %}">LogIn</a></li>
		{% endif %}
	</ul>

		<br><br><h2>{{ err }}</h2>
		<br><br>
		<fieldset>
		 <legend><h2>Add Restaurant</h2></legend>
		 <form action="{% url 'ResRev:add_rest' %}" method="post">
			 {% csrf_token %}
			 <input type="text" name="name" placeholder="Name"><br><br>
			 <input type="text" name="descrip" placeholder="Description"><br><br>
			 <input type="text" name="cate" placeholder="Category"><br><br>
			 <input type="text" name="contact" placeholder="Contact"><br><br>
			 <input type="submit" value="Submit">
		 </form>
		</fieldset>
	<form>
			<br><br>recommend Menu: <br><br>
			<input type="text" name="rec1" placeholder="recommend Menu 1"><br><br>
			<input type="text" name="rec2" placeholder="recommend Menu 1"><br><br>
			<input type="text" name="rec3" placeholder="recommend Menu 1"><br><br>
	</form>
	</body>
</html>

ResRev/templates/register.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<style>
	body {margin:0;}

	font-family: Arial;
	}

	* {
	box-sizing: border-box;
	}

	fieldset {
  display: block;
  margin-left: 10px;
  margin-right: 2px;
  padding-top: 0.35em;
  padding-bottom: 0.625em;
  padding-left: 0.75em;
  padding-right: 0.75em;
  border: 2px groove (internal value);
  width:300px;
	font-size:18px;
	}

	.button {
	  background-color: #4CAF50; /* Green */
	  border: none;
	  color: white;
	  padding: 16px 32px;
	  text-align: center;
	  text-decoration: none;
	  display: inline-block;
	  font-size: 16px;
		margin-left: 10px;
	  margin-right: 2px;
	  -webkit-transition-duration: 0.4s; /* Safari */
	  transition-duration: 0.4s;
	  cursor: pointer;
	}
	.button1 {
	  background-color: white;
	  color: black;
	  border: 2px solid #000000;
		position: relative;
	}

	.button1:hover {
	  background-color: #000000;
	  color: white;
	}

	ul {
	  list-style-type: none;
	  margin: 0;
	  padding: 0;
	  overflow: hidden;
	  background-color: black	;
	  position: fixed;
	  top: 0;
	  width: 100%;
	}

	li {
	  float: left;
	}

	li a {
	  display: block;
	  color: white;
	  text-align: center;
	  padding: 14px 16px;
	  text-decoration: none;
	}

	.rightmenu {
	  background-color: green;
	}
	</style>
</head>
	<body>
	<ul>
	  <li><a>ResRev</a></li>
	</ul>


		<br><br>
		<fieldset>
		 <legend><h2>Fill your Data</h2></legend>
		 {{ err }}
		 <form action="{% url 'ResRev:registering' %}" method="post">
			 {% csrf_token %}
			 <input type="text" name="username" placeholder="Enter Username"><br><br>
			 <input type="password" name="password" placeholder="Enter your Password"><br><br>
			 <input type="password" name="Cpassword" placeholder="Confirm your Password"><br><br>
			 <input type="text" name="name" placeholder="Name"><br><br>
			 <textarea rows="4" cols="50" input type="textarea" name="contact" placeholder="Contact"></textarea><br><br>
			 <input type="submit" value="Submit">
		 </form>
		</fieldset>
	</body>
</html>

ResRev/templates/restaurant_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<style>
	body {margin:0;}

	font-family: Arial;
	}

	* {
	box-sizing: border-box;
	}

	fieldset {
  display: block;
  margin-left: 10px;
  margin-right: 2px;
  padding-top: 0.35em;
  padding-bottom: 0.625em;
  padding-left: 0.75em;
  padding-right: 0.75em;
  border: 2px groove (internal value);
  width:300px;
	font-size:18px;
	}
	.left {
	  float:left;
	  width:50%;
	}
	.right {
	  float:left;
	  width:50%;
	}
	.button {
	  background-color: #4CAF50; /* Green */
	  border: none;
	  color: white;
	  padding: 16px 32px;
	  text-align: center;
	  text-decoration: none;
	  display: inline-block;
	  font-size: 16px;
		margin-left: 10px;
	  margin-right: 2px;
	  -webkit-transition-duration: 0.4s; /* Safari */
	  transition-duration: 0.4s;
	  cursor: pointer;
	}
	.button1 {
	  background-color: white;
	  color: black;
	  border: 2px solid #000000;
		position: relative;
	}

	.button1:hover {
	  background-color: #000000;
	  color: white;
	}

	ul {
	  list-style-type: none;
	  margin: 0;
	  padding: 0;
	  overflow: hidden;
	  background-color: black	;
	  position: fixed;
	  top: 0;
	  width: 100%;
	}

	li {
	  float: left;
	}

	li a {
	  display: block;
	  color: white;
	  text-align: center;
	  padding: 14px 16px;
	  text-decoration: none;
	}

	.rightmenu {
	  background-color: green;
	}
	</style>
</head>
	<body>
	<ul>
	  <li><a>ResRev</a></li>
		{% if user.is_authenticated %}
			<li style="float:right"><a class="rightmenu" href="{% url 'ResRev:logout' %}">LogOut</a></li>
		{% else %}
		  <li style="float:right"><a class="rightmenu" href="{% url 'ResRev:frontPage' %}">LogIn</a></li>
		{% endif %}

	</ul>
	{% if some_flag %}
    <div id="some_flag" title="Some Flag">
        <p>Register Finished!</p>
    </div>
	{% endif %}

		<br><br><h2>{{ err }}</h2>
		<fieldset>
		 <legend><h2>Restaurant Data</h2></legend>
		 Restaurant Name : {{ rest_info.name }}<br>
		 Desription : {{ rest_info.description }}<br>
		 Category : {{ rest_info.category }}<br>
		 Rating : {{ rest_info.rating }}<br>
		 Rating From Good Reviewer : {{ rest_info.g_rating }}<br>
		</fieldset>
		{% if list_review %}
			<h1>Review</h1>
			{% for review in list_review %}
				<fieldset>
				 <legend><h3>Review {{ forloop.counter }}</h2></legend>
					User : {{ review.reviewer.user }}<br>
					Class : {{ review.reviewer.clas }}<br>
					comment : {{ review.comment }}<br>
					rating : {{ review.rating }}<br>
					like : {{ review.like }}<br>
				</fieldset>
			{% endfor %}
		{% else %}
			<h3>No Review yet </h3>
		{% endif %}

		{% if user.is_authenticated %}
			<form action="{% url 'ResRev:add_review' rest_info.id %}" method="post">
			{% csrf_token %}
			<fieldset>
			 <legend><h2>Restaurant Data</h2></legend>
			 Name : {{ user.get_username }}</br>
			 Comment : <textarea rows="4" cols="50" input type="textarea" name="comment" placeholder="comment"></textarea>
			 Rating : 1<input type="radio" name="Rating" value=1> 2<input type="radio" name="Rating" value=2> 3<input type="radio" name="Rating" value=3> 4<input type="radio" name="Rating" value=4> 5<input type="radio" name="Rating" value=5></br>
			</fieldset>
			<input type="submit" class="button button1" value="Submit">
		{% else %}
		    <p>Welcome, new user. Please log in.</p>
		{% endif %}

	</body>
</html>